export const projects = [
  { id: 1, cat: 'logistics',      tag: 'Logistics',       tool: 'Simio',   image: '/images/image1.jpeg',  title: 'Warehouse Management System',          desc: 'Comprehensive warehouse simulation covering picking, placing, routing, and inventory flow. Delivered actionable insights for efficiency improvement and customer satisfaction.',  region: '🌍 Global' },
  { id: 2, cat: 'logistics',      tag: 'Logistics',       tool: 'Simio',   image: '/images/image5.png',   title: 'Picking & Placing Materials',           desc: 'Simulation analysis of warehouse picking and placing operations to drive improvements in efficiency, accuracy, and customer satisfaction.',                                     region: '📦 Warehouse' },
  { id: 3, cat: 'manufacturing',  tag: 'Manufacturing',   tool: 'Simio',   image: '/images/image6.jpeg',  title: 'Prosthodontic Material Workshop',       desc: 'In-house manufacturing setup simulation for a prosthodontic material production workshop, streamlining workflow and reducing material waste.',                                region: '🏭 Industrial' },
  { id: 4, cat: 'manufacturing',  tag: 'Manufacturing',   tool: 'Simio',   image: '/images/image7.png',   title: 'Town Workshop — DoE Optimization',      desc: 'Design of Experiment-driven simulation for a town workshop facility, evaluating multiple configurations to identify the most efficient operational setup.',                    region: '🔧 Industrial' },
  { id: 5, cat: 'service',        tag: 'Service',         tool: 'Arena',   image: '/images/image8.png',   title: 'Restaurant Proof of Concept',           desc: 'Full simulation of restaurant operations including customer arrival patterns, order processing, kitchen throughput, and service time optimization for a student client.',     region: '🍽️ Service' },
  { id: 6, cat: 'academic',       tag: 'Academic/R&D',    tool: 'Simio',   image: '/images/image9.png',   title: 'Chemical Industry — R&D Concept',       desc: 'Concept implementation simulation for the R&D department of a chemical industry client, modeling experimental workflows and resource utilization patterns.',                  region: '🧪 R&D' },
  { id: 7, cat: 'healthcare',     tag: 'Healthcare',      tool: 'FlexSim', image: '/images/image10.png',  title: 'Healthcare Facility Digital Twin',       desc: 'Multi-phase digital twin of a healthcare setting including patient flow, staff allocation, and facility layout optimization. Three-scenario analysis for strategic decision-making.', region: '🏥 Enterprise', featured: true },
  { id: 8, cat: 'academic',       tag: 'Academic',        tool: 'FlexSim', image: '/images/image13.png',  title: 'Academic Proof of Concept',             desc: 'Rigorous simulation-based proof of concept for an academic client, demonstrating process feasibility and identifying key performance improvement opportunities.',               region: '🎓 Academic' },
  { id: 9, cat: 'academic',       tag: 'Academic',        tool: 'FlexSim', image: '/images/image14.png',  title: 'Brownies Packing — Food Production',    desc: 'Simulation of a brownies packing line for academic process analysis, demonstrating packaging automation potential and workforce optimization.',                                region: '🎓 Academic' },
  { id: 10, cat: 'logistics',     tag: 'Logistics',       tool: 'Arena',   image: '/images/image16.png',  title: 'Airport Baggage Handling',              desc: 'Simulation of an airport baggage handling system to minimize turnaround times, reduce errors, and optimize staffing levels during peak operations.',                            region: '✈️ Aviation' },
  { id: 11, cat: 'manufacturing', tag: 'Manufacturing',   tool: 'FlexSim', image: '/images/image17.png',  title: 'Flexible Manufacturing System (FMS)',   desc: 'Enterprise-scale FMS simulation for a company in France, modeling complex routing, machine scheduling, and real-time optimization of production resources.',                 region: '🇫🇷 France' },
  { id: 12, cat: 'logistics',     tag: 'Logistics',       tool: 'Arena',   image: '/images/image18.png',  title: 'Filling Station Queuing Problem',       desc: 'Discrete-event simulation of a filling station to analyze queuing behavior, waiting times, and optimal service counter configuration to reduce customer wait.',                region: '⛽ Service' },
  { id: 13, cat: 'manufacturing', tag: 'Manufacturing',   tool: 'FlexSim', image: '/images/image19.png',  title: 'Wood Manufacturing — Bottleneck Removal', desc: 'End-to-end wood manufacturing simulation identifying critical bottlenecks and modeling targeted interventions to increase overall equipment effectiveness.',                  region: '🌲 Industrial' },
  { id: 14, cat: 'service',       tag: 'Service',         tool: 'Arena',   image: '/images/image20.png',  title: 'Salon Setup — Malaysia',               desc: "Simulation of a salon's operational flow in Malaysia, modeling appointment scheduling, walk-in customers, and staff allocation for peak and off-peak periods.",               region: '🇲🇾 Malaysia' },
  { id: 15, cat: 'academic',      tag: 'Academic',        tool: 'FlexSim', image: '/images/image22.png',  title: 'University Lab — Singapore',           desc: 'Simulation-based lab setup optimization for a university in Singapore, modeling equipment utilization, student workflows, and experiment scheduling efficiency.',             region: '🇸🇬 Singapore' },
  { id: 16, cat: 'manufacturing', tag: 'Manufacturing',   tool: 'Simio',   image: '/images/image23.png',  title: 'Automobile Assembly Line',             desc: 'Full simulation of automobile assembly for a Pakistani manufacturer, identifying bottlenecks and optimizing production throughput at the subpart and system level.',         region: '🇵🇰 Pakistan' },
  { id: 17, cat: 'service',       tag: 'Service',         tool: 'Simio',   image: '/images/image26.png',  title: 'Drive-Through & Walk-In Simulation',   desc: 'Multi-scenario simulation for drive-through and walk-in customer service operations, analyzing queue dynamics and service efficiency across three design variants.',         region: '🚗 Service' },
  { id: 18, cat: 'manufacturing', tag: 'Manufacturing',   tool: 'Simio',   image: '/images/image30.png',  title: 'Automobile Manufacturing — Pakistan',  desc: 'Detailed simulation of an automobile manufacturing plant in Pakistan, optimizing production scheduling, reducing idle time, and improving line efficiency.',                  region: '🇵🇰 Pakistan' },
  { id: 19, cat: 'manufacturing', tag: 'Manufacturing',   tool: 'FlexSim', image: '/images/image31.png',  title: 'Vertical Forming Simulation',          desc: 'Detailed simulation of a vertical forming process to identify production inefficiencies and model alternative process configurations for improved throughput.',              region: '🏭 Industrial' },
]

export const services = [
  { num: '01', icon: '🏭', title: 'Manufacturing Simulation',   desc: 'Production line balancing, bottleneck analysis, FMS optimization, and assembly line simulation using Simio, FlexSim & Arena.', items: ['Line balancing & throughput analysis', 'Bottleneck identification & removal', 'Flexible Manufacturing Systems (FMS)', 'Design of Experiments (DoE)'] },
  { num: '02', icon: '📦', title: 'Warehouse & Logistics',      desc: 'End-to-end warehouse management simulation including picking, placing, routing, and inventory flow optimization.',              items: ['Warehouse layout optimization', 'Picking & placing systems', 'Inventory flow modeling', 'Ambulance & emergency routing'] },
  { num: '03', icon: '🏥', title: 'Healthcare Simulation',      desc: 'Patient flow modeling, facility planning digital twins, and resource optimization for hospitals and clinics.',                   items: ['Patient flow analysis', 'Healthcare facility planning', 'Digital twin development', 'Staff & resource scheduling'] },
  { num: '04', icon: '✈️', title: 'Airport & Transportation',   desc: 'Airport baggage handling simulation, queuing system analysis, and transportation network modeling.',                            items: ['Baggage handling systems', 'Queuing & throughput analysis', 'Drive-through simulation', 'Walk-in customer flow'] },
  { num: '05', icon: '🤖', title: 'AI & Digital Transformation',desc: 'Advanced AI-powered solutions aligned to Industry 4.0 standards, from proof-of-concept to enterprise deployment.',             items: ['Industry 4.0 integration', 'AI-powered optimization', 'Proof of concept development', 'R&D simulation support'] },
  { num: '06', icon: '🔬', title: 'Academic & Research',        desc: 'Supporting university research labs and student projects with rigorous simulation methodology across Singapore, Malaysia, and beyond.', items: ['University lab setups', 'Proof-of-concept projects', 'Academic research support', 'Industry-academia collaboration'] },
]

export const tagClass: Record<string, string> = {
  'Logistics':      'logistics-tag',
  'Manufacturing':  'manufacturing-tag',
  'Healthcare':     'healthcare-tag',
  'Academic':       'academic-tag',
  'Academic/R&D':   'academic-tag',
  'Service':        'service-tag',
}
